sudo: false
language: d
d:
  - dmd
  - ldc

os:
  - linux
  - osx

env:
  - ARCH=x86_64

before_install:
  - dub fetch trial

script:
  - dub run trial:runner
  - dub build -b debug --compiler=$DC --arch=$ARCH
  - for file in ./examples/*.d; do; echo "Running example $file"; dub $file; done
